# # Visit https://github.com/lowlighter/metrics#-documentation for full reference
# name: Metrics
# on:
#   # Schedule updates (each hour)
#   schedule: [{cron: "0 * * * *"}]
#   # Lines below let you run workflow manually and on each commit
#   workflow_dispatch:
#   push: {branches: ["master", "main"]}
# jobs:
#   github-metrics:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write
#     steps:
#       - uses: lowlighter/metrics@latest
#         with:
#           # Your GitHub token
#           # The following scopes are required:
#           #  - public_access (default scope)
#           #  - read:user
#           #  - read:org
#           # The following additional scopes may be required:
#           #  - read:org      (for organization related metrics)
#           #  - read:user     (for user related data)
#           #  - read:packages (for some packages related data)
#           #  - repo          (optional, if you want to include private repositories)
#           token: ${{ secrets.METRICS_TOKEN }}

#           # Options
#           user: loganbek
#           template: classic
#           base: header, activity, community, repositories, metadata
#           config_timezone: America/Los_Angeles
#           plugin_followup: yes
#           plugin_followup_archived: yes
#           plugin_followup_indepth: yes
#           plugin_followup_sections: repositories
#           plugin_habits: yes
#           plugin_habits_charts: yes
#           plugin_habits_charts_type: classic
#           plugin_habits_days: 14
#           plugin_habits_facts: yes
#           plugin_habits_from: 200
#           plugin_habits_languages_limit: 100
#           plugin_habits_languages_threshold: 0%
#           plugin_isocalendar: yes
#           plugin_isocalendar_duration: full-year
#           plugin_languages: yes
#           plugin_languages_analysis_timeout: 100
#           plugin_languages_analysis_timeout_repositories: 100
#           plugin_languages_categories: markup, programming
#           plugin_languages_colors: github
#           plugin_languages_details: bytes-size, percentage
#           plugin_languages_indepth: yes
#           plugin_languages_limit: 100
#           plugin_languages_other: yes
#           plugin_languages_recent_categories: markup, programming
#           plugin_languages_recent_days: 12
#           plugin_languages_recent_load: 300
#           plugin_languages_sections: most-used
#           plugin_lines: yes
#           plugin_lines_history_limit: 1
#           plugin_lines_repositories_limit: 4
#           plugin_lines_sections: base
#           plugin_people: yes
#           plugin_people_limit: 24
#           plugin_people_size: 28
#           plugin_people_types: followers, following
#           plugin_reactions: yes
#           plugin_reactions_display: absolute
#           plugin_reactions_limit: 200
#           plugin_reactions_limit_discussions: 100
#           plugin_reactions_limit_discussions_comments: 100
#           plugin_reactions_limit_issues: 100
#           plugin_repositories: yes
#           plugin_repositories_order: featured, pinned, starred, random
#           plugin_sponsors: yes
#           plugin_sponsors_sections: goal, list, about
#           plugin_sponsors_size: 24
#           plugin_sponsors_title: Sponsor Me!
#           plugin_sponsorships: yes
#           plugin_sponsorships_sections: amount, sponsorships
#           plugin_sponsorships_size: 24
#           plugin_stargazers: yes
#           plugin_stargazers_charts: yes
#           plugin_stargazers_charts_type: chartist
#           plugin_stargazers_worldmap: yes
#           plugin_stargazers_worldmap_sample: 4
#           plugin_stars: yes
#           plugin_stars_limit: 4
#           plugin_topics: yes
#           plugin_topics_limit: 100
#           plugin_topics_mode: starred
#           plugin_topics_sort: stars